### ISSUE TITLE
Allow option to set the from: address

### ISSUE THREAD

**Issue by pzearfoss** [bitrise-io/steps-email-with-mailgun#11]
It'd be helpful for us to specify the from address and sender as an option to the plugin.  Right now we're locked into "Bitrise Mailgun Step <postmaster@$domain>"

**Comment by viktorbenei** [comment]
Good idea, added to our list - there are quite a few open issues for this Step now :)

**Comment by godrei** [comment]
Hi,
a new version ([2.1.0](https://github.com/bitrise-io/steps-email-with-mailgun/releases/tag/2.1.0)) will be available in setplib soon, which got a new input `from_email `.
