### ISSUE TITLE
Support for file attachement ?

### ISSUE THREAD

**Issue by mackoj** [bitrise-io/steps-email-with-mailgun#12]
Hi,

It would be great if this step could support mail attachment.

**Comment by viktorbenei** [comment]
Thanks for the request!

I registered it into our list, but feel free to send a Pull Request if you have the time to implement this!

**Comment by godrei** [comment]
Hi,
a new version ([2.1.0](https://github.com/bitrise-io/steps-email-with-mailgun/releases/tag/2.1.0)) will be available in setplib soon, which got a new input `attachments `.
